---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-express.fullname" . }}
  labels:
    name: {{ include "node-express.fullname" . }}
    helm.sh/chart: {{ include "node-express.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "node-express.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}