apiVersion: v1
kind: Service
metadata:
  name: node-express
  labels:
    name: node-express
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-express
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
      - image: gcr.io/proj-genesis/node-express:latest
        name: node-express
        ports:
        - containerPort: 8080
          name: node